// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMZTJXA0gSI2vz5QVNtlPnM-tO-VSV_uw',
    appId: '1:267698667354:web:cbb3f5db6e742baa537d63',
    messagingSenderId: '267698667354',
    projectId: 'booksage-64a03',
    authDomain: 'booksage-64a03.firebaseapp.com',
    storageBucket: 'booksage-64a03.appspot.com',
    measurementId: 'G-DWCXTEMYTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdfQvc6pk21ogOxrETI6yTcow_5SH11Og',
    appId: '1:267698667354:android:d1d212132294d702537d63',
    messagingSenderId: '267698667354',
    projectId: 'booksage-64a03',
    storageBucket: 'booksage-64a03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvCHkUmO_eb3S_D2UQY4UR9vNVIXnRv5o',
    appId: '1:267698667354:ios:add9dc6706df5a81537d63',
    messagingSenderId: '267698667354',
    projectId: 'booksage-64a03',
    storageBucket: 'booksage-64a03.appspot.com',
    iosBundleId: 'com.example.reading',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvCHkUmO_eb3S_D2UQY4UR9vNVIXnRv5o',
    appId: '1:267698667354:ios:6dc006172f1368e5537d63',
    messagingSenderId: '267698667354',
    projectId: 'booksage-64a03',
    storageBucket: 'booksage-64a03.appspot.com',
    iosBundleId: 'com.example.reading.RunnerTests',
  );
}
